# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'SeleniumTests' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @wait = Selenium::WebDriver::Wait.new(timeout: 10)
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'oneHundred' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:id, 'v1').send_keys('100')
    @driver.find_element(:id, 'submit').click
    expect(@wait.until { @driver.find_element(:xpath, "//p[@id='num']") }.text).to eq('10.000052895642693')
  end

  it 'unknown' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:id, 'submit').click
    expect(@wait.until { @driver.find_element(:xpath, "//p[@id='num']") }.text).to eq('Unknown!')
  end
end
